/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import Controller.AppointmentController;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author 3C Tech
 */
public class AppointmentInformation extends javax.swing.JFrame {
    private AppointmentController appointmentController;
    private Connection conn;
    private PreparedStatement pst;
    private ResultSet rs;
    
    /**
     * Creates new form AppointmentInformation
     */
    public AppointmentInformation() {
        initComponents();
        appointmentController = new AppointmentController();
        setNextAppointmentNo();
        updateTable();
        addPetIdListener();
        jtxtAppointmentNo.setEditable(false);
        attachEventHandlers();
    }
    
    public void search() {
    String srch = searchbox.getText();
    try {
        String sql = "SELECT * FROM appointments WHERE PetName LIKE '%" + srch + "%' OR AppointmentNo LIKE '%" + srch + "%'";
        Connection conn = appointmentController.getConnections();
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}
    private void attachEventHandlers() {
        jbtnBack.addActionListener(evt -> jbtnBackActionPerformed(evt));
        searchbox.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            search();
        }
    });
    }
    
    private void addPetIdListener() {
        jtxtPetID.addActionListener(evt -> fetchPetDetails());
    }

    private void fetchPetDetails() {
        Vector<String> petDetails = appointmentController.getPetDetails(jtxtPetID.getText());
        if (petDetails.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pet ID not found");
        } else {
            jtxtPetName.setText(petDetails.get(0));
            jtxtOwnerName.setText(petDetails.get(1));
            jtxtTelephone.setText(petDetails.get(2));
        }
    }

    private void updateTable() {
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        tableModel.setRowCount(0);
        Vector<Vector<String>> data = appointmentController.getAllAppointments();
        for (Vector<String> row : data) {
            tableModel.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jbtnAdd = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jbtnBack = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        searchbox = new javax.swing.JTextField();
        jtxtAppointmentNo = new javax.swing.JTextField();
        jtxtPetID = new javax.swing.JTextField();
        jtxtPetName = new javax.swing.JTextField();
        jtxtOwnerName = new javax.swing.JTextField();
        jtxtTelephone = new javax.swing.JTextField();
        jtxtDate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jtxtTime = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102), 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102), 5));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnAdd.setBackground(new java.awt.Color(255, 204, 204));
        jbtnAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnAdd.setText("Add ");
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 170, 50));

        jbtnUpdate.setBackground(new java.awt.Color(255, 204, 204));
        jbtnUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 170, 50));

        jbtnReset.setBackground(new java.awt.Color(255, 204, 204));
        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 170, 50));

        jbtnDelete.setBackground(new java.awt.Color(255, 204, 204));
        jbtnDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 170, 50));

        jbtnBack.setBackground(new java.awt.Color(255, 204, 204));
        jbtnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnBack.setText("Back");
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 170, 50));

        jbtnExit.setBackground(new java.awt.Color(255, 204, 204));
        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 170, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vet8-ezgif.com-resize.gif"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 160, 130));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 240, 600));

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 102), 5, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel3.setText("Appointment No");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 20));

        jLabel4.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel4.setText("Pet ID");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 60, -1));

        jLabel5.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel5.setText("Pet Name");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel6.setText("Owner's Name");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel7.setText("Telephone");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel8.setText("Appointment Date");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 20));

        jLabel9.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel9.setText("Search by Appointment No or Pet ID:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, -1, -1));

        searchbox.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        searchbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchboxActionPerformed(evt);
            }
        });
        jPanel3.add(searchbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 550, 180, 30));

        jtxtAppointmentNo.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jPanel3.add(jtxtAppointmentNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 400, 30));

        jtxtPetID.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jPanel3.add(jtxtPetID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 400, 30));

        jtxtPetName.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jPanel3.add(jtxtPetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 400, 30));

        jtxtOwnerName.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jPanel3.add(jtxtOwnerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 400, 30));

        jtxtTelephone.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jPanel3.add(jtxtTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 400, 30));

        jtxtDate.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jtxtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDateActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 400, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Appointment No", "Pet ID", "Pet Name", "Owner Name", "Telephone", "Appointment Date", "Appointment Time"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 560, 230));

        jLabel10.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel10.setText("Appointment Time");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jtxtTime.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jtxtTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTimeActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 400, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 620, 600));

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        jLabel1.setText("Appointment Information");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(166, 166, 166))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 870, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 890, 710));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
        // Check if any of the fields are empty
    if(jtxtAppointmentNo.getText().isEmpty() || jtxtPetID.getText().isEmpty() ||
       jtxtPetName.getText().isEmpty() || jtxtOwnerName.getText().isEmpty() ||
       jtxtTelephone.getText().isEmpty() || jtxtDate.getText().isEmpty() ||jtxtTime.getText().isEmpty()
       ) {
        JOptionPane.showMessageDialog(this, "Please fill in all fields.");
        return; // Exit the method if any field is empty
    }
    
    // If all fields are filled, proceed to add the appointment
    appointmentController.addAppointment(jtxtAppointmentNo.getText(), jtxtPetID.getText(), jtxtPetName.getText(),
            jtxtOwnerName.getText(), jtxtTelephone.getText(), jtxtDate.getText(),jtxtTime.getText());
    JOptionPane.showMessageDialog(this, "Record Added");
    updateTable();
    setNextAppointmentNo();
    resetFields();
        
    }//GEN-LAST:event_jbtnAddActionPerformed
    


    
    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
         DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
    int selectedRow = jTable1.getSelectedRow();

    if (selectedRow == -1) { // Check if no row is selected
        JOptionPane.showMessageDialog(this, "Please select a row to update.");
        return; // Exit the method
    }

    int id = Integer.parseInt(tableModel.getValueAt(selectedRow, 0).toString());

    appointmentController.updateAppointment(id, jtxtPetID.getText(), jtxtPetName.getText(), jtxtOwnerName.getText(),
            jtxtTelephone.getText(), jtxtDate.getText(), jtxtTime.getText());
    JOptionPane.showMessageDialog(this, "Record Updated");
    updateTable();
    setNextAppointmentNo();
    resetFields();
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        resetFields();
        setNextAppointmentNo();
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
    int selectedRow = jTable1.getSelectedRow();

    if (selectedRow == -1) { // Check if no row is selected
        JOptionPane.showMessageDialog(this, "Please select a row to delete.");
        return; // Exit the method
    }

    int id = Integer.parseInt(tableModel.getValueAt(selectedRow, 0).toString());

    appointmentController.deleteAppointment(id);
    JOptionPane.showMessageDialog(this, "Record Deleted");
    updateTable();
    setNextAppointmentNo();
    resetFields();
    }//GEN-LAST:event_jbtnDeleteActionPerformed
    
    
    private void resetFields() {
        jtxtPetID.setText("");
        jtxtPetName.setText("");
        jtxtOwnerName.setText("");
        jtxtTelephone.setText("");
        jtxtDate.setText("");
        jtxtTime.setText("");
    }

    private void setNextAppointmentNo() {
        jtxtAppointmentNo.setText(String.valueOf(appointmentController.getNextAppointmentNo()));
    }

    
    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        Home home = new Home();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbtnBackActionPerformed
    
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        JFrame frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "MySQL Connector",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jtxtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDateActionPerformed

    private void searchboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchboxActionPerformed
        search();
    }//GEN-LAST:event_searchboxActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        int selectedRow = jTable1.getSelectedRow();
        jtxtAppointmentNo.setText(tableModel.getValueAt(selectedRow, 0).toString());
        jtxtPetID.setText(tableModel.getValueAt(selectedRow, 1).toString());
        jtxtPetName.setText(tableModel.getValueAt(selectedRow, 2).toString());
        jtxtOwnerName.setText(tableModel.getValueAt(selectedRow, 3).toString());
        jtxtTelephone.setText(tableModel.getValueAt(selectedRow, 4).toString());
        jtxtDate.setText(tableModel.getValueAt(selectedRow, 5).toString());
        jtxtTime.setText(tableModel.getValueAt(selectedRow, 6).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jtxtTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTimeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppointmentInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppointmentInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppointmentInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppointmentInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(() -> new AppointmentInformation().setVisible(true));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JTextField jtxtAppointmentNo;
    private javax.swing.JTextField jtxtDate;
    private javax.swing.JTextField jtxtOwnerName;
    private javax.swing.JTextField jtxtPetID;
    private javax.swing.JTextField jtxtPetName;
    private javax.swing.JTextField jtxtTelephone;
    private javax.swing.JTextField jtxtTime;
    private javax.swing.JTextField searchbox;
    // End of variables declaration//GEN-END:variables
}
