/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controller.BillingController;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author 3C Tech
 */
public class Billing extends javax.swing.JFrame {
    private BillingController billingController;
    
    public Billing() {
        initComponents();
        billingController = new BillingController();
    }
    
    public void ItemCost() {
        double sum = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum += Double.parseDouble(jTable1.getValueAt(i, 2).toString());
        }
        jtxtSubTotal.setText(Double.toString(sum));
        double cTotal1 = Double.parseDouble(jtxtSubTotal.getText());
        double cTax = (cTotal1 * 3.9) / 100;
        jtxtTax.setText(String.format("Rs. %.2f", cTax));
        jtxtSubTotal.setText(String.format("Rs. %.2f", cTotal1));
        jtxtTotal.setText(String.format("Rs. %.2f", cTotal1 + cTax));
    }

    public void Change() {
        double sum = 0;
        double tax = 3.9;
        double cash = Double.parseDouble(jtxtDisplay.getText());
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum += Double.parseDouble(jTable1.getValueAt(i, 2).toString());
        }
        double cTax = (sum * tax) / 100;
        double cChange = cash - (sum + cTax);
        jtxtChange.setText(String.format("Rs. %.2f", cChange));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnPic4 = new javax.swing.JButton();
        jbtnPic1 = new javax.swing.JButton();
        jbtnPic2 = new javax.swing.JButton();
        jbtnPic3 = new javax.swing.JButton();
        jbtnPic5 = new javax.swing.JButton();
        jbtnPic6 = new javax.swing.JButton();
        jbtnPic7 = new javax.swing.JButton();
        jbtnPic8 = new javax.swing.JButton();
        jbtnPic9 = new javax.swing.JButton();
        jbtnPic10 = new javax.swing.JButton();
        jbtnPic11 = new javax.swing.JButton();
        jbtnPic12 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jbtn8 = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtn7 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtnDot = new javax.swing.JButton();
        jbtnC = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jtxtTotal = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtDisplay = new javax.swing.JTextField();
        jtxtChange = new javax.swing.JTextField();
        jcboPayment = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jbtnRemove = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnPay = new javax.swing.JButton();
        jbtnBack = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnPic4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnPic4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pro4 (1).png"))); // NOI18N
        jbtnPic4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPic4ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPic4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 90, 100));

        jbtnPic1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnPic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pro1 (1).png"))); // NOI18N
        jbtnPic1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPic1ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 100));

        jbtnPic2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnPic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pro2 (1).png"))); // NOI18N
        jbtnPic2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPic2ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPic2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 90, 100));

        jbtnPic3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnPic3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pro3 (1).png"))); // NOI18N
        jbtnPic3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPic3ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPic3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 90, 100));

        jbtnPic5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnPic5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pro5 (1).png"))); // NOI18N
        jbtnPic5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPic5ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPic5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 100, 90));

        jbtnPic6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnPic6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pro6 (1).png"))); // NOI18N
        jbtnPic6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPic6ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPic6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 90, 90));

        jbtnPic7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnPic7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pro7 (1).png"))); // NOI18N
        jbtnPic7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPic7ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPic7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 90, 90));

        jbtnPic8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnPic8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pro8 (1).png"))); // NOI18N
        jbtnPic8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPic8ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPic8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 90, 90));

        jbtnPic9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnPic9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pro9 (1).png"))); // NOI18N
        jbtnPic9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPic9ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPic9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 100, 100));

        jbtnPic10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnPic10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pro10 (1).png"))); // NOI18N
        jbtnPic10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPic10ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPic10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 90, 100));

        jbtnPic11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnPic11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pro11 (1).png"))); // NOI18N
        jbtnPic11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPic11ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPic11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 90, 100));

        jbtnPic12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnPic12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pro12 (1).png"))); // NOI18N
        jbtnPic12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPic12ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPic12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 90, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 420, 330));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn8.setText("8");
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 70, 70));

        jbtn9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn9.setText("9");
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 70, 70));

        jbtn7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn7.setText("7");
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 70));

        jbtn4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn4.setText("4");
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 70, 70));

        jbtn5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn5.setText("5");
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 70, 70));

        jbtn6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn6.setText("6");
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 70, 70));

        jbtn1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn1.setText("1");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 70, 70));

        jbtn2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn2.setText("2");
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 70, 70));

        jbtn3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn3.setText("3");
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 70, 70));

        jbtn0.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn0.setText("0");
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 70, 70));

        jbtnDot.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnDot.setText(".");
        jbtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDotActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 70, 70));

        jbtnC.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnC.setText("C");
        jbtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 70, 70));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 330));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Quantity", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 300, 330));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Sub Total");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Tax");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Total");

        jtxtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSubTotalActionPerformed(evt);
            }
        });

        jtxtTax.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jtxtTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtTotal)
                            .addComponent(jtxtTax))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jtxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 180));

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Payment Method");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Cash");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Change");

        jtxtDisplay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jtxtChange.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jcboPayment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcboPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", " " }));
        jcboPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboPaymentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcboPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtDisplay)
                            .addComponent(jtxtChange))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcboPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 320, 180));

        jPanel6.setBackground(new java.awt.Color(255, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jbtnRemove.setBackground(new java.awt.Color(255, 51, 102));
        jbtnRemove.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnRemove.setText("Remove");
        jbtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveActionPerformed(evt);
            }
        });

        jbtnReset.setBackground(new java.awt.Color(255, 51, 102));
        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jbtnPay.setBackground(new java.awt.Color(255, 51, 102));
        jbtnPay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPay.setText("Pay");
        jbtnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPayActionPerformed(evt);
            }
        });

        jbtnBack.setBackground(new java.awt.Color(255, 51, 102));
        jbtnBack.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnBack.setText("Back");
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });

        jbtnExit.setBackground(new java.awt.Color(255, 51, 102));
        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnPay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jbtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 290, 180));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 960, 200));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
            
    private void jtxtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSubTotalActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        jtxtDisplay.setText(Enternumber + jbtn9.getText());
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        jtxtDisplay.setText(Enternumber + jbtn5.getText());
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtnPic2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPic2ActionPerformed
        addItemToTable("Black Hawk Adult Grain Free Chicken Wet Dog Food", 800.00);
    }//GEN-LAST:event_jbtnPic2ActionPerformed

    private void jbtnPic7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPic7ActionPerformed
        addItemToTable("Blackcat Chicken Tenders Cat Treats", 1350.00);
    }//GEN-LAST:event_jbtnPic7ActionPerformed

    private void jbtnPic6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPic6ActionPerformed
        addItemToTable("Black Hawk Adult Grain Free Wet Cat Food – Chicken With Peas Broth And Gravy", 465.00);
    }//GEN-LAST:event_jbtnPic6ActionPerformed

    private void jbtnPic9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPic9ActionPerformed
        addItemToTable("All in One Tonic Bird Vitamin – 50ml", 699.00);
    }//GEN-LAST:event_jbtnPic9ActionPerformed

    private void jbtnPic10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPic10ActionPerformed
        addItemToTable("Pet Transport Cage Crate IATA Approved Airline Cat Carriers- Small", 25000.00);
    }//GEN-LAST:event_jbtnPic10ActionPerformed

    private void jbtnPic12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPic12ActionPerformed
        addItemToTable("Black Hawk Adult Grain Free Lamb Wet Dog Food", 890.00);
    }//GEN-LAST:event_jbtnPic12ActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        jtxtDisplay.setText(Enternumber + jbtn7.getText());
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        jtxtDisplay.setText(Enternumber + jbtn8.getText());
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        jtxtDisplay.setText(Enternumber + jbtn4.getText());
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        jtxtDisplay.setText(Enternumber + jbtn6.getText());
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        jtxtDisplay.setText(Enternumber + jbtn1.getText());
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        jtxtDisplay.setText(Enternumber + jbtn2.getText());
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        jtxtDisplay.setText(Enternumber + jbtn3.getText());
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        jtxtDisplay.setText(Enternumber + jbtn0.getText());
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCActionPerformed
        jtxtDisplay.setText("");
        jtxtChange.setText("");
    }//GEN-LAST:event_jbtnCActionPerformed

    private void jbtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDotActionPerformed
       if (!jtxtDisplay.getText().contains(".")) {
            jtxtDisplay.setText(jtxtDisplay.getText() + jbtnDot.getText());
        } 
    }//GEN-LAST:event_jbtnDotActionPerformed

    private void jbtnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPayActionPerformed
        if (jcboPayment.getSelectedItem().equals("Cash")) {
            Change();
        } else {
            jtxtChange.setText("");
            jtxtDisplay.setText("");
        }
        saveBillingData();
    }//GEN-LAST:event_jbtnPayActionPerformed
   
    private void saveBillingData() {
        try {
            double subTotal = Double.parseDouble(jtxtSubTotal.getText().replace("Rs. ", ""));
            double tax = Double.parseDouble(jtxtTax.getText().replace("Rs. ", ""));
            double total = Double.parseDouble(jtxtTotal.getText().replace("Rs. ", ""));
            billingController.saveBillingData(subTotal, tax, total);
            JOptionPane.showMessageDialog(this, "Billing data saved successfully!");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error parsing billing data!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void addItemToTable(String itemName, double priceOfItem) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{itemName, "1", priceOfItem});
        ItemCost();
    }
    
    private void jbtnPic1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPic1ActionPerformed
        addItemToTable("Black Hawk Adult Grain Free Beef Wet Dog Food", 850.00);
    }//GEN-LAST:event_jbtnPic1ActionPerformed

    private void jbtnPic3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPic3ActionPerformed
        addItemToTable("Beef Bone Rawhide Chews Dog Treats 4Pack", 1300.00);
    }//GEN-LAST:event_jbtnPic3ActionPerformed

    private void jbtnPic4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPic4ActionPerformed
        addItemToTable("Mavlab Fido’s Glucosamine Joint Health 100 Tablet", 2400.00);
    }//GEN-LAST:event_jbtnPic4ActionPerformed

    private void jbtnPic5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPic5ActionPerformed
        addItemToTable("Black Hawk Adult Cat Chicken and Rice", 8200.00);
    }//GEN-LAST:event_jbtnPic5ActionPerformed

    private void jbtnPic8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPic8ActionPerformed
        addItemToTable("Kitzyme Conditioning Tablets 300", 2576.00);
    }//GEN-LAST:event_jbtnPic8ActionPerformed

    private void jbtnPic11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPic11ActionPerformed
        addItemToTable("Cat Carry Bag Portable Cat Dog Travel Carrier Bag", 12500.00);
    }//GEN-LAST:event_jbtnPic11ActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        jtxtChange.setText("");
        jtxtTax.setText("");
        jtxtTotal.setText("");
        jtxtSubTotal.setText("");
        jtxtDisplay.setText("");
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int RemoveItem = jTable1.getSelectedRow();
        if (RemoveItem >= 0) {
            model.removeRow(RemoveItem);
        }
        ItemCost();
        if (jcboPayment.getSelectedItem().equals("Cash")) {
            Change();
        } else {
            jtxtChange.setText("");
            jtxtDisplay.setText("");
        }
        
    }//GEN-LAST:event_jbtnRemoveActionPerformed
    
    private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "MySQL Connector", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        Home home = new Home();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbtnBackActionPerformed

    private void jcboPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcboPaymentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        java.awt.EventQueue.invokeLater(() -> new Billing().setVisible(true));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnC;
    private javax.swing.JButton jbtnDot;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnPay;
    private javax.swing.JButton jbtnPic1;
    private javax.swing.JButton jbtnPic10;
    private javax.swing.JButton jbtnPic11;
    private javax.swing.JButton jbtnPic12;
    private javax.swing.JButton jbtnPic2;
    private javax.swing.JButton jbtnPic3;
    private javax.swing.JButton jbtnPic4;
    private javax.swing.JButton jbtnPic5;
    private javax.swing.JButton jbtnPic6;
    private javax.swing.JButton jbtnPic7;
    private javax.swing.JButton jbtnPic8;
    private javax.swing.JButton jbtnPic9;
    private javax.swing.JButton jbtnRemove;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JComboBox<String> jcboPayment;
    private javax.swing.JTextField jtxtChange;
    private javax.swing.JTextField jtxtDisplay;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables
}
